spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/k8_1_0/department/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/k8_1_0/user/**
springdoc:
  swagger-ui:
    urls:
      - name: user
        url: /v3/api-docs/user
      - name: department
        url: /v3/api-docs/department
