# department-service
spring:
  application:
    name: department-service
# springdoc:
#   packageToScan: com.department
eureka:
  instance:
    instance-id: ${spring.application.name}-lh-${server.port}
# springdoc:
#   packages-to-scan: com.departementService

