# department-service
spring:
  application:
    name: department-service

# eureka:
#   instance:
#     instance-id: ${spring.application.name}-${random.uuid}
# springdoc:
#   packages-to-scan: com.departementService
springdoc:
  packagesToScan: com.department
